name: Build EXE Release

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # ใช้คำสั่ง PowerShell หาไฟล์ .csproj ทั้งหมดในโปรเจกต์
    - name: Check where is my project file
      shell: pwsh
      run: |
        Get-ChildItem -Path . -Filter *.csproj -Recurse | Select-Object FullName

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore

    - name: Build Solution
      shell: pwsh
      run: |
        $projFile = (Get-ChildItem -Path . -Filter *.csproj -Recurse | Select-Object -First 1).FullName
        # แก้ตรง Platform เป็น "AnyCPU" (พิมพ์ติดกันตามใน .csproj)
        msbuild $projFile /p:Configuration=Release /p:Platform="x64"
        
    - name: Prepare Artifact
      shell: pwsh
      run: |
        if (!(Test-Path "build_output")) { mkdir build_output }
        Get-ChildItem -Path "**/bin/Release/" -Recurse -Include *.exe, *.dll, *.config | Copy-Item -Destination "build_output" -Force
        ls build_output

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: External-App-Output
        path: build_output/
