name: Build EXE Release

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore  # ลบชื่อไฟล์ออก ให้มันหาเองอัตโนมัติ

    - name: Build Solution
      run: msbuild External.csproj /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Prepare Artifact
      # ย้ายไฟล์ทั้งหมดไปไว้ในโฟลเดอร์เดียวเพื่อให้โหลดง่าย
      run: |
        mkdir build_output
        copy bin\Release\*.exe build_output\
        copy bin\Release\*.dll build_output\
        copy bin\Release\*.config build_output\

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: External-FF-Program
        path: build_output/
